# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{svn-transform}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jared Morgan"]
  s.date = %q{2009-10-28}
  s.description = %q{Given a Subversion repository, svn-transform creates a new repo that is by 
default identical, but allows changes to files, for example all or some of the 
properties on each file can be moved from the properties to YAML prepended to 
the body of the file. Primarily useful prior to conversions to other repository 
types such as git.
}
  s.email = %q{jmorgan@morgancreative.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/example_helper.rb",
     "examples/fixtures/dir_props.rb",
     "examples/fixtures/original.rb",
     "examples/fixtures/result.rb",
     "examples/svn-transform/dir_example.rb",
     "examples/svn-transform/file_example.rb",
     "examples/svn-transform/transform/extension_example.rb",
     "examples/svn-transform/transform/newline_example.rb",
     "examples/svn-transform/transform/noop_example.rb",
     "examples/svn-transform/transform/props_to_yaml_example.rb",
     "examples/svn-transform_example.rb",
     "lib/svn-transform.rb",
     "lib/svn-transform/dir.rb",
     "lib/svn-transform/file.rb",
     "lib/svn-transform/session.rb",
     "lib/svn-transform/transform/extension.rb",
     "lib/svn-transform/transform/newline.rb",
     "lib/svn-transform/transform/noop.rb",
     "lib/svn-transform/transform/props_to_yaml.rb"
  ]
  s.homepage = %q{http://github.com/jm81/svn-props-to-yaml}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Copy Subversion repository, with the ability to alter files}
  s.test_files = [
    "examples/example_helper.rb",
     "examples/fixtures/dir_props.rb",
     "examples/fixtures/original.rb",
     "examples/fixtures/result.rb",
     "examples/svn-transform/dir_example.rb",
     "examples/svn-transform/file_example.rb",
     "examples/svn-transform/transform/extension_example.rb",
     "examples/svn-transform/transform/newline_example.rb",
     "examples/svn-transform/transform/noop_example.rb",
     "examples/svn-transform/transform/props_to_yaml_example.rb",
     "examples/svn-transform_example.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<svn-fixture>, ["= 0.2.0"])
      s.add_development_dependency(%q<spicycode-micronaut>, [">= 0"])
    else
      s.add_dependency(%q<svn-fixture>, ["= 0.2.0"])
      s.add_dependency(%q<spicycode-micronaut>, [">= 0"])
    end
  else
    s.add_dependency(%q<svn-fixture>, ["= 0.2.0"])
    s.add_dependency(%q<spicycode-micronaut>, [">= 0"])
  end
end
